apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-api
  namespace: nimbus-system
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-ui
  namespace: nimbus-system
spec:
  template:
    spec:
      containers:
        - name: ui
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-worker
  namespace: nimbus-system
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: Never
