apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ui-nginx-configmap.yaml
patches:
  - path: nodeport-ui.yaml
  - path: delete-ingress.yaml
  - path: image-pull-policy.yaml
  - path: ui-nginx-patch.yaml

images:
  - name: nimbus/iaas-api
    newName: docker.io/nimbus/iaas-api
    newTag: latest
