{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnamePrefix }}-mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnamePrefix }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fullnamePrefix }}-mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: {{ .Values.fullnamePrefix }}-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.fullnamePrefix }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fullnamePrefix }}-mysql
spec:
  serviceName: {{ .Values.fullnamePrefix }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fullnamePrefix }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.fullnamePrefix }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullnamePrefix }}-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullnamePrefix }}-mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullnamePrefix }}-mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullnamePrefix }}-mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: [mysqladmin, ping, -h, localhost]
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [mysqladmin, ping, -h, localhost]
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
{{- end }}
