{{- $platform := .Values.platform -}}
{{- if or $platform.multus.install $platform.kubevirt.featureGates.enabled $platform.cdi.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnamePrefix }}-platform
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "virtforge.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fullnamePrefix }}-platform
  labels:
    {{- include "virtforge.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
rules:
  - apiGroups: [kubevirt.io]
    resources: [kubevirt]
    verbs: [get, patch]
  - apiGroups: [apps]
    resources: [daemonsets]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [namespaces, pods]
    verbs: [get, list, watch, create]
  - apiGroups: [cdi.kubevirt.io]
    resources: [cdis]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [get, list, watch, create, update, patch, apply]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fullnamePrefix }}-platform
  labels:
    {{- include "virtforge.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fullnamePrefix }}-platform
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnamePrefix }}-platform
    namespace: {{ .Values.namespace }}
{{- end }}
