apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnamePrefix }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ROOT_PASSWORD: {{ .Values.secrets.rootPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
