apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnamePrefix }}-config
  namespace: {{ .Values.namespace }}
{{- include "virtfoundry.validateBridgeNames" . }}
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
    logger:
      level: {{ .Values.config.logLevel | quote }}
      format: "json"
    security:
      jwt_expire: {{ .Values.config.jwtExpire }}
    kubevirt:
      enabled: {{ .Values.config.kubevirtEnabled }}
      kubeconfig: ""
      namespace: "default"
    database:
      driver: {{ .Values.store.driver | quote }}
    observability:
      velas_explore_url: ""
    networking:
      public:
        enabled: {{ .Values.platform.networking.public.enabled }}
        mode: {{ .Values.platform.networking.public.mode | quote }}
        cidr: {{ .Values.platform.networking.public.cidr | quote }}
        gateway: {{ .Values.platform.networking.public.gateway | quote }}
        dns: {{ .Values.platform.networking.public.dns | toJson }}
        ip_pool_start: {{ .Values.platform.networking.public.ipPool.start | quote }}
        ip_pool_end: {{ .Values.platform.networking.public.ipPool.end | quote }}
        bridge_name: {{ .Values.platform.networking.public.bridge.name | quote }}
        nad_name: {{ .Values.platform.networking.public.nad.name | quote }}
        nad_namespace: {{ .Values.platform.networking.public.nad.namespace | quote }}
      isolated:
        bridge_name: {{ .Values.platform.networking.isolated.bridge.name | quote }}
      vm:
        default_network: {{ .Values.platform.networking.vm.defaultNetwork | quote }}
        allow_pod_network: {{ .Values.platform.networking.vm.allowPodNetwork }}
    storage:
      default_class: {{ .Values.platform.storage.defaultClass | quote }}
      snapshot_class: {{ .Values.platform.storage.snapshotClass | quote }}
      windows_boot_size_gi: {{ .Values.platform.storage.windowsBootSizeGi }}
      windows_iso_size_gi: {{ .Values.platform.storage.windowsISOSizeGi }}
