{{- include "virtfoundry.validateSecrets" . }}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnamePrefix }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ include "virtfoundry.rootPasswordKey" . }}: {{ include "virtfoundry.rootPassword" . | quote }}
  {{ include "virtfoundry.jwtSecretKey" . }}: {{ include "virtfoundry.jwtSecret" . | quote }}
{{- end }}
