#!/usr/bin/env bash
# Copies the CRDs into charts/virtfoundry-crds/manifests from their sources of truth:
#   - virtfoundry/operator  config/crd/bases   (generated by controller-gen)
#   - virtfoundry/vks       charts/virtfoundry-vks/templates/crd
# OPERATOR_DIR / VKS_DIR point at local checkouts; otherwise main is cloned shallowly.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEST="${DEST:-${ROOT}/charts/virtfoundry-crds/manifests}"
REF_OPERATOR="${OPERATOR_REF:-main}"
REF_VKS="${VKS_REF:-main}"

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

fetch() { # name ref dir-var
  local name="$1" ref="$2" dir="$3"
  if [[ -n "${dir}" ]]; then echo "${dir}"; return; fi
  git clone --quiet --depth 1 --branch "${ref}" "https://github.com/virtfoundry/${name}.git" "${TMP}/${name}"
  echo "${TMP}/${name}"
}

OPERATOR="$(fetch operator "${REF_OPERATOR}" "${OPERATOR_DIR:-}")"
VKS="$(fetch vks "${REF_VKS}" "${VKS_DIR:-}")"

rm -rf "${DEST}" && mkdir -p "${DEST}"
cp "${OPERATOR}"/config/crd/bases/*.yaml "${DEST}/"
cp "${VKS}"/charts/virtfoundry-vks/templates/crd/*.yaml "${DEST}/"
echo "synced $(ls "${DEST}" | wc -l | tr -d ' ') CRDs into ${DEST}"
