apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nimbus
  namespace: nimbus-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: iaas.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nimbus-api
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: nimbus-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nimbus-ui
                port:
                  number: 80
