apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nimbus-system
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-statefulset.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - ui-deployment.yaml
  - ingress.yaml
