name: Docs external links

on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check links in docs
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --no-progress --accept 200,206,429 --exclude-mail 'docs/**/*.md' README.md
          fail: false
